import { useEffect, useMemo, useState } from 'react';
import Box from '@mui/material/Box';
import Card from '@mui/material/Card';
import Typography from '@mui/material/Typography';
import Alert from '@mui/material/Alert';
import { DataGrid, type GridColDef } from '@mui/x-data-grid';
import PageHeader from '../../components/PageHeader';
import StatusTag from '../../components/StatusTag';
import EmptyState from '../../components/EmptyState';
import EarningsSummary from '../../components/taxiCompany/EarningsSummary';
import { useFleet } from '../../components/taxiCompany/FleetContext';
import { formatCurrency } from '../../utils/format';
import {
  getFleetEarnings,
  getFleetPayouts,
  type FleetDriverEarnings,
  type FleetEarnings,
  type FleetPayout,
} from '../../services/fleet';
import { tokens } from '../../theme';

type VehicleActivityRow = {
  id: string;
  plateNumber: string;
  model: string;
  drivingHoursToday: number;
  screenTimeHoursToday: number;
  distanceKmToday: number;
};

const PAYOUT_STATUS_VARIANT = {
  Paid: 'live',
  Processing: 'warn',
  Scheduled: 'outline',
} as const;

export default function EarningsPage() {
  const { vehicles } = useFleet();

  const [earnings, setEarnings] = useState<FleetEarnings | null>(null);
  const [payouts, setPayouts] = useState<FleetPayout[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const controller = new AbortController();

    Promise.all([getFleetEarnings(undefined, controller.signal), getFleetPayouts(controller.signal)])
      .then(([earningsResult, payoutResult]) => {
        setEarnings(earningsResult);
        setPayouts(payoutResult);
      })
      .catch((e: unknown) => {
        if (controller.signal.aborted) return;
        setError(e instanceof Error ? e.message : 'Could not load earnings.');
      })
      .finally(() => {
        if (!controller.signal.aborted) setLoading(false);
      });

    return () => controller.abort();
  }, []);

  const vehicleRows = useMemo<VehicleActivityRow[]>(
    () =>
      vehicles.map((v) => ({
        id: v.id,
        plateNumber: v.plateNumber,
        model: v.year ? `${v.model} (${v.year})` : v.model,
        drivingHoursToday: v.drivingHoursToday,
        screenTimeHoursToday: v.screenTimeHoursToday,
        distanceKmToday: v.distanceKmToday,
      })),
    [vehicles],
  );

  const driverColumns = useMemo<GridColDef<FleetDriverEarnings>[]>(
    () => [
      { field: 'driverName', headerName: 'Driver', flex: 1, minWidth: 160 },
      { field: 'shiftCount', headerName: 'Shifts', flex: 0.5, minWidth: 90, type: 'number' },
      { field: 'activeHours', headerName: 'Active hrs', flex: 0.6, minWidth: 110, type: 'number' },
      {
        field: 'total',
        headerName: 'Generated',
        flex: 0.7,
        minWidth: 120,
        type: 'number',
        valueFormatter: (value: number) => formatCurrency(value, { decimals: 2 }),
      },
    ],
    [],
  );

  const vehicleColumns = useMemo<GridColDef<VehicleActivityRow>[]>(
    () => [
      { field: 'plateNumber', headerName: 'Plate', flex: 0.7, minWidth: 110 },
      { field: 'model', headerName: 'Model', flex: 1, minWidth: 160 },
      { field: 'drivingHoursToday', headerName: 'Driving hrs', flex: 0.7, minWidth: 110, type: 'number' },
      { field: 'screenTimeHoursToday', headerName: 'Verified screen hrs', flex: 0.8, minWidth: 150, type: 'number' },
      { field: 'distanceKmToday', headerName: 'Distance (km)', flex: 0.7, minWidth: 120, type: 'number' },
    ],
    [],
  );

  const payoutColumns = useMemo<GridColDef<FleetPayout>[]>(
    () => [
      { field: 'period', headerName: 'Period', flex: 1, minWidth: 140 },
      {
        field: 'amount',
        headerName: 'Amount',
        flex: 0.8,
        minWidth: 120,
        type: 'number',
        valueFormatter: (value: number) => formatCurrency(value),
      },
      {
        field: 'paidAtUtc',
        headerName: 'Paid on',
        flex: 0.8,
        minWidth: 130,
        valueGetter: (_v, row) => (row.paidAtUtc ? new Date(row.paidAtUtc).toLocaleDateString() : '—'),
      },
      {
        field: 'status',
        headerName: 'Status',
        flex: 0.7,
        minWidth: 130,
        renderCell: (params) => (
          <StatusTag
            label={params.row.status}
            variant={PAYOUT_STATUS_VARIANT[params.row.status] ?? 'neutral'}
          />
        ),
      },
    ],
    [],
  );

  return (
    <>
      <PageHeader
        title="Earnings"
        subtitle="What your drivers generated, and how each vehicle contributed."
      />

      {error && <Alert severity="error" sx={{ mb: '20px' }}>{error}</Alert>}

      <Card sx={{ p: '20px', mb: '24px' }}>
        <Typography sx={{ fontSize: 11.5, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.04em', color: 'text.secondary' }}>
          Generated by your fleet
        </Typography>
        <Typography sx={{ fontWeight: 700, fontSize: 16, mb: '12px' }}>Summary</Typography>
        <EarningsSummary columns={4} />
        <Typography sx={{ fontSize: 12.5, color: 'text.secondary', mt: '12px' }}>
          Earnings accrue per driver for the shifts they work. How they are shared between your
          company and your drivers is set by your agreement with them, not by AdzOnRoad.
        </Typography>
      </Card>

      <Card sx={{ p: 0, mb: '24px' }}>
        <Box sx={{ padding: '18px 22px' }}>
          <Typography sx={{ fontWeight: 700, fontSize: 16 }}>By driver, this month</Typography>
          <Typography sx={{ fontSize: 12.5, color: 'text.secondary', mt: '4px' }}>
            Base, hourly and premium-area bonus, as settled for each completed shift.
          </Typography>
        </Box>
        {loading ? (
          <EmptyState title="Loading earnings…" description="Fetching settled shifts." />
        ) : !earnings || earnings.byDriver.length === 0 ? (
          <EmptyState
            title="Nothing earned yet this month"
            description="Earnings appear once a driver completes a shift with a screen fitted and reporting."
          />
        ) : (
          <Box sx={{ height: 380 }}>
            <DataGrid
              rows={earnings.byDriver}
              getRowId={(row) => row.driverId}
              columns={driverColumns}
              disableRowSelectionOnClick
              pageSizeOptions={[5, 10]}
              initialState={{ pagination: { paginationModel: { pageSize: 10 } } }}
              sx={{ border: 'none' }}
            />
          </Box>
        )}
      </Card>

      <Card sx={{ p: 0, mb: '24px' }}>
        <Box sx={{ padding: '18px 22px' }}>
          <Typography sx={{ fontWeight: 700, fontSize: 16 }}>Per-vehicle activity today</Typography>
          <Typography sx={{ fontSize: 12.5, color: 'text.secondary', mt: '4px' }}>
            Verified screen hours count only playback that correlated to a GPS fix — the evidence
            an advertiser is billed against.
          </Typography>
        </Box>
        {vehicleRows.length === 0 ? (
          <EmptyState title="No vehicles yet" description="Add a car to start tracking activity." />
        ) : (
          <Box sx={{ height: 400 }}>
            <DataGrid
              rows={vehicleRows}
              columns={vehicleColumns}
              disableRowSelectionOnClick
              pageSizeOptions={[5, 10]}
              initialState={{ pagination: { paginationModel: { pageSize: 10 } } }}
              sx={{ border: 'none' }}
            />
          </Box>
        )}
      </Card>

      <Card sx={{ p: 0 }}>
        <Box sx={{ padding: '18px 22px' }}>
          <Typography sx={{ fontWeight: 700, fontSize: 16 }}>Payout history</Typography>
        </Box>
        {payouts.length === 0 ? (
          <Box sx={{ borderTop: `1px solid ${tokens.border}` }}>
            <EmptyState
              title="No payouts yet"
              description="Payouts appear here once AdzOnRoad settles a period with your company."
            />
          </Box>
        ) : (
          <Box sx={{ height: 360, borderTop: `1px solid ${tokens.border}` }}>
            <DataGrid
              rows={payouts}
              columns={payoutColumns}
              disableRowSelectionOnClick
              pageSizeOptions={[5, 10]}
              initialState={{ pagination: { paginationModel: { pageSize: 5 } } }}
              sx={{ border: 'none' }}
            />
          </Box>
        )}
      </Card>
    </>
  );
}
